### ISSUE TITLE
HandlerHelper in the sample site missing case for the Facebook handler

### ISSUE THREAD

**Issue by jfarley** [Aguafrommars/DymamicAuthProviders#53]
The startup specifies Facebook provider support via
```
            dynamicBuilder
                .AddFacebook()
```
but the case for the Facebook handler is missing from the helper.

**Comment by aguacongas** [comment]
Hi @jfarley can you provide code ? You probably miss a using statement or a package

**Comment by aguacongas** [comment]
fixed in #54

**Comment by aguacongas** [comment]
@jfarley thx for the PR
